import { Metadata } from 'next';
import ThemeRegistry from './ThemeRegistry';

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};

export default function RootLayout({
    children,
}: {
    children: React.ReactNode;
}) {
    return (
        <html lang="en">
            <body
                style={{
                    position: 'relative',
                    minHeight: '100vh',
                    paddingBottom: '70px',
                }}
            >
                <ThemeRegistry options={{ key: 'mui' }}>
                    {children}
                </ThemeRegistry>
            </body>
        </html>
    );
}
